baseURL = "https://axiom-example.netlify.app"

title = "Axiom Example"
languageCode = "en-us"
defaultContentLanguage = "en"

theme = "axiom"

paginate = 2
canonifyURLs = false
summaryLength = 40
rssLimit = 100
enableEmoji = true
enableRobotsTXT = true
pluralizelisttitles = false

[permalinks]
posts = "/:filename"

[params]
mainSections = ["posts"]
copyrightYear = 2019
# Go Reference time: Mon Jan 2 15:04:05 MST 2006
dateFormat = "Jan 2, 2006 3:04PM"
highlight = "dark"

[params.brand]
domain = "example.com"
email = "info@example.com"

[params.social]
email = "mailto:urverda@mail.ustc.edu.cn"
github = "https://github.com/user"
footer = ["email", "github"]

#[params.logo]
#inline = true
#path = "images/header.jpg"

[params.image]
width = "2048"
height = "1024"
#faviconIco = "favicon.ico"
#faviconAlt = "image/brand/favicon.png"
#icon1To1 = "image/brand/icon-1-1.png"
#icon2To1 = "image/brand/icon-2-1.png"
#default = "image/page-default.webp"

[params.font]
type = ""
path = ""
files = []

[params.cdn]
provider = "local"
type = "image"

#[params.cloudinary]
#host = "https://res.cloudinary.com/CLOUD_NAME/"
#version = ""
#image = "image/upload/"
#raw = "raw/upload/"
#video = "video/upload/"

#[params.cloudinary.presets]
#base = "f_auto,q_auto/"
#page = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
#feature = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"
#summary = "w_auto,dpr_auto,c_scale,f_auto,q_auto/"

[outputs]
home = ["HTML", "ATOM"]
section = ["HTML"]
taxonomy = ["HTML"]
taxonomyTerm = ["HTML"]

[outputFormats]
[outputFormats.ATOM]
name = "ATOM"
baseName = "feed"
mediaType = "application/atom+xml"

[mediaTypes]
[mediaTypes."application/atom+xml"]
suffixes = ["atom"]

[markup]
[markup.goldmark]
[markup.goldmark.extensions]
definitionList = false
footnote = true
linkify = false
strikethrough = false
table = true
taskList = false
typographer = false
[markup.goldmark.renderer]
unsafe = true
[markup.goldmark.parser]
attribute = false
[markup.highlight]
codeFences = true
noClasses = false
tabWidth = 2
# lineNos = true
# lineNumbersInTable = false

[menu]
[[menu.main]]
url = "/"
name = "Home"
weight = 1

[[menu.foot]]
url = "/"
name = "Home"
weight = 1

[[menu.main]]
url = "/"
name = "About"
weight = 2

[[menu.foot]]
url = "/about/"
name = "About"
weight = 2

[[menu.main]]
url = "/research/"
name = "Research"
weight = 3

[[menu.foot]]
url = "/research/"
name = "Research"
weight = 3

[[menu.main]]
url = "/publication/"
name = "Publication"
weight = 4

[[menu.foot]]
url = "/publication/"
name = "Publication"
weight = 4

[languages]
[languages."en"]
weight = 1
languageName = "English"